// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hmvsqsizlmcporabbdtv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhtdnNxc2l6bG1jcG9yYWJiZHR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0MzkwODYsImV4cCI6MjA3MTAxNTA4Nn0.L2eRWrBniyLJHTSWjByqD5uJaUESyUDsTtxtp8Iy8t0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});